version: '3.8'
services:
  reactapp:
    container_name: reactapp
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    image: maxi3390/react:latest
    ports:
      - 3000:3000
    volumes:
      - './app:/app'
